using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YAGOT_2._0.Migrations
{
    /// <inheritdoc />
    public partial class Group3IdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                DECLARE
                    entity_table text;
                    old_sequence text;
                    new_sequence text;
                    identity_state text;
                BEGIN
                    FOREACH entity_table IN ARRAY ARRAY[
                        'carts', 'cartitems', 'orders', 'orderitems', 'products', 'categories'
                    ]
                    LOOP
                        SELECT is_identity INTO identity_state
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = entity_table
                          AND column_name = 'id';

                        IF identity_state = 'NO' THEN
                            old_sequence := pg_get_serial_sequence(
                                format('public.%I', entity_table), 'id');

                            EXECUTE format(
                                'ALTER TABLE %I ALTER COLUMN id DROP DEFAULT', entity_table);

                            IF old_sequence IS NOT NULL THEN
                                EXECUTE format('ALTER SEQUENCE %s OWNED BY NONE', old_sequence);
                            END IF;

                            new_sequence := entity_table || '_id_identity_seq';
                            EXECUTE format(
                                'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME %I)',
                                entity_table, new_sequence);
                        END IF;

                        EXECUTE format(
                            'SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE(MAX(id), 0) + 1, false) FROM %I',
                            entity_table, 'id', entity_table);
                    END LOOP;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Identity conversion is intentionally retained on downgrade. Reverting
            // to legacy serial defaults would reintroduce the integrity issue.
        }
    }
}
