// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YAGOT_2._0.Models;

#nullable disable

namespace YAGOT_2._0.Migrations
{
    [DbContext(typeof(NeondbContext))]
    partial class NeondbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<int?>("UserSiteId")
                        .HasColumnType("integer");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("carts_pkey");

                    b.HasIndex("UserSiteId");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cartitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cartid")
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("cartitems_pkey");

                    b.HasIndex("Cartid");

                    b.HasIndex("Productid");

                    b.ToTable("cartitems", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Deliveryorder", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Orderid"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Secondphonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secondphonenumber");

                    b.HasKey("Orderid")
                        .HasName("deliveryorders_pkey");

                    b.ToTable("deliveryorders", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("Orderdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Paymentstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentstatus")
                        .HasDefaultValueSql("'Unpaid'::character varying");

                    b.Property<string>("Receipturl")
                        .HasColumnType("text")
                        .HasColumnName("receipturl");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<decimal>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.Property<string>("Trackingnumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trackingnumber");

                    b.Property<int?>("UserSiteId")
                        .HasColumnType("integer");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex("UserSiteId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("accountname");

                    b.Property<string>("Accountnumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accountnumber");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Fulladdress")
                        .HasColumnType("text")
                        .HasColumnName("fulladdress");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<string>("Paymentimagepath")
                        .HasColumnType("text")
                        .HasColumnName("paymentimagepath");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Paymentnotes")
                        .HasColumnType("text")
                        .HasColumnName("paymentnotes");

                    b.Property<string>("Recipientname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("recipientname");

                    b.Property<string>("Recipientphone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipientphone");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("Transferreferencenumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transferreferencenumber");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("orderdetails_pkey");

                    b.HasIndex(new[] { "Orderid" }, "IX_orderdetails_orderid")
                        .IsUnique();

                    b.ToTable("orderdetails", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Unitprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unitprice");

                    b.HasKey("Id")
                        .HasName("orderitems_pkey");

                    b.HasIndex("Orderid");

                    b.HasIndex("Productid");

                    b.ToTable("orderitems", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Paymentmethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountholdername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accountholdername");

                    b.Property<string>("Accountnumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accountnumber");

                    b.Property<string>("Cardcolor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cardcolor");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Storesettingsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("storesettingsid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("paymentmethods_pkey");

                    b.HasIndex(new[] { "Storesettingsid" }, "ix_paymentmethods_storesettingsid");

                    b.ToTable("paymentmethods", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("brand");

                    b.Property<int>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("Stockquantity")
                        .HasColumnType("integer")
                        .HasColumnName("stockquantity");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex("Categoryid");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Securitylog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Deviceinfo")
                        .HasColumnType("text")
                        .HasColumnName("deviceinfo");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<int?>("Riskscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("riskscore");

                    b.Property<int?>("UserSiteId")
                        .HasColumnType("integer");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("securitylogs_pkey");

                    b.HasIndex("UserSiteId");

                    b.ToTable("securitylogs", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Storesetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contactemail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("contactemail")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Instagramlink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("instagramlink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Tiktoklink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("tiktoklink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Twitterlink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("twitterlink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Whatsappnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("whatsappnumber")
                        .HasDefaultValueSql("''::text");

                    b.HasKey("Id")
                        .HasName("storesettings_pkey");

                    b.ToTable("storesettings", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'Customer'::character varying");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.UserSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("'Customer'::character varying");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("UserSite_pkey");

                    b.ToTable("UserSite", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("browser");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Device")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("device");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<DateTime>("Visitdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visitdate")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("Visitorname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("visitorname");

                    b.HasKey("Id")
                        .HasName("visits_pkey");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Carts")
                        .HasForeignKey("UserSiteId");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cartitem", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Cart", "Cart")
                        .WithMany("Cartitems")
                        .HasForeignKey("Cartid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart");

                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("Cartitems")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_cart");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserSiteId");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderdetail", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Order", "Order")
                        .WithOne("Orderdetail")
                        .HasForeignKey("YAGOT_2._0.Models.Orderdetail", "Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orderdetails_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderitem", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Order", "Order")
                        .WithMany("Orderitems")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order");

                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("Orderitems")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_order");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Paymentmethod", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Storesetting", "Storesettings")
                        .WithMany("Paymentmethods")
                        .HasForeignKey("Storesettingsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paymentmethods_storesettings");

                    b.Navigation("Storesettings");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Securitylog", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Securitylogs")
                        .HasForeignKey("UserSiteId");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.Navigation("Cartitems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.Navigation("Orderdetail");

                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.Navigation("Cartitems");

                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Storesetting", b =>
                {
                    b.Navigation("Paymentmethods");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.UserSite", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Securitylogs");
                });
#pragma warning restore 612, 618
        }
    }
}
