// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YAGOT_2._0.Models;

#nullable disable

namespace YAGOT_2._0.Migrations
{
    [DbContext(typeof(NeondbContext))]
    partial class NeondbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.CapabilityEventReceipt", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliveryid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<byte[]>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payloadsha256");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordedatutc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.HasKey("DeliveryId")
                        .HasName("capability_event_receipts_pkey");

                    b.HasIndex(new[] { "SiteId", "Revision" }, "ix_capability_event_receipts_site_revision");

                    b.ToTable("capability_event_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_capability_receipts_decision", "decision IN ('Applied', 'Equal', 'Stale', 'EqualConflict')");

                            t.HasCheckConstraint("ck_capability_receipts_hash_length", "octet_length(payloadsha256) = 32");

                            t.HasCheckConstraint("ck_capability_receipts_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_capability_receipts_site_id", "siteid >= 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.CapabilitySyncCheckpoint", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("health");

                    b.Property<DateTimeOffset>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastattemptatutc");

                    b.Property<long?>("LastAttemptedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("lastattemptedrevision");

                    b.Property<string>("LastFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lastfailurecategory");

                    b.Property<long?>("LastObservedRemoteRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("lastobservedremoterevision");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastsuccessatutc");

                    b.Property<long?>("LastSuccessfullyAppliedRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("lastsuccessfullyappliedrevision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.HasKey("SiteId")
                        .HasName("capability_sync_checkpoints_pkey");

                    b.ToTable("capability_sync_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_capability_checkpoint_applied_revision", "lastsuccessfullyappliedrevision IS NULL OR lastsuccessfullyappliedrevision >= 1");

                            t.HasCheckConstraint("ck_capability_checkpoint_attempted_revision", "lastattemptedrevision IS NULL OR lastattemptedrevision >= 1");

                            t.HasCheckConstraint("ck_capability_checkpoint_observed_revision", "lastobservedremoterevision IS NULL OR lastobservedremoterevision >= 1");

                            t.HasCheckConstraint("ck_capability_checkpoint_site_id", "siteid >= 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("carts_pkey");

                    b.HasIndex(new[] { "Userid" }, "ux_carts_userid")
                        .IsUnique();

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cartitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cartid")
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<int?>("RetailPriceId")
                        .HasColumnType("integer")
                        .HasColumnName("retail_price_id");

                    b.HasKey("Id")
                        .HasName("cartitems_pkey");

                    b.HasIndex("Productid");

                    b.HasIndex("RetailPriceId");

                    b.HasIndex(new[] { "Cartid", "Productid", "RetailPriceId" }, "ix_cartitems_cart_product_retail");

                    b.ToTable("cartitems", null, t =>
                        {
                            t.HasCheckConstraint("ck_cartitems_quantity_nonnegative", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Deliveryorder", b =>
                {
                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Secondphonenumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("secondphonenumber");

                    b.HasKey("Orderid")
                        .HasName("deliveryorders_pkey");

                    b.ToTable("deliveryorders", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.LocalCapabilitySnapshot", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appliedatutc");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalogversion");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contractversion");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveatutc");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generatedatutc");

                    b.Property<byte[]>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payloadsha256");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshotjson");

                    b.HasKey("SiteId")
                        .HasName("local_capability_snapshots_pkey");

                    b.ToTable("local_capability_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_local_capability_contract_version", "contractversion = 1");

                            t.HasCheckConstraint("ck_local_capability_hash_length", "octet_length(payloadsha256) = 32");

                            t.HasCheckConstraint("ck_local_capability_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_local_capability_site_id", "siteid >= 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.LocalSiteStateSnapshot", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contractversion");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveatutc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresatutc");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<int>("OriginalDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("originaldurationdays");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sitename");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("siteurl");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startdate");

                    b.HasKey("SiteId")
                        .HasName("local_site_state_snapshots_pkey");

                    b.ToTable("local_site_state_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_local_site_state_contract_version", "contractversion = 1");

                            t.HasCheckConstraint("ck_local_site_state_duration", "originaldurationdays > 0");

                            t.HasCheckConstraint("ck_local_site_state_mode", "mode IN ('Online', 'Development', 'Offline')");

                            t.HasCheckConstraint("ck_local_site_state_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_local_site_state_site_id", "siteid = 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("admin_note");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelledat");

                    b.Property<string>("Currencycode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("YER")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("Discounttotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_total");

                    b.Property<decimal?>("Finalfulfilledamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("finalfulfilledamount");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("Orderdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("orderdate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<DateTime?>("Paymentreviewedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paymentreviewedat");

                    b.Property<int?>("Paymentreviewedbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("paymentreviewedbyuserid");

                    b.Property<string>("Paymentstatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentstatus")
                        .HasDefaultValueSql("'Unpaid'::character varying");

                    b.Property<DateTime?>("Paymentverifiedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paymentverifiedat");

                    b.Property<int?>("Paymentverifiedbyuserid")
                        .HasColumnType("integer")
                        .HasColumnName("paymentverifiedbyuserid");

                    b.Property<string>("Promotionsnapshotjson")
                        .HasColumnType("jsonb")
                        .HasColumnName("promotion_snapshot_json");

                    b.Property<string>("Receipturl")
                        .HasColumnType("text")
                        .HasColumnName("receipturl");

                    b.Property<decimal>("Spendamountdiscount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("spend_amount_discount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<bool>("Stockdeducted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("stockdeducted");

                    b.Property<DateTime?>("TimeState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<decimal>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.Property<string>("Trackingnumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trackingnumber");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Workflowstate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workflowstate");

                    b.HasKey("Id")
                        .HasName("orders_pkey");

                    b.HasIndex(new[] { "CancelledAt" }, "ix_orders_cancelledat");

                    b.HasIndex(new[] { "Orderdate" }, "ix_orders_orderdate")
                        .IsDescending();

                    b.HasIndex(new[] { "Status", "Orderdate" }, "ix_orders_status_orderdate")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "Userid", "Orderdate" }, "ix_orders_userid_orderdate")
                        .IsDescending(false, true);

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_dh03_cancelledat", "(status = 'Cancelled') = (cancelledat IS NOT NULL)");

                            t.HasCheckConstraint("ck_orders_dh03_conflict", "workflowstate <> 'ConflictAwaitingDecision' OR (status = 'Pending' AND NOT stockdeducted AND paymentstatus <> 'Paid' AND paymentverifiedat IS NULL AND paymentverifiedbyuserid IS NULL AND finalfulfilledamount IS NULL)");

                            t.HasCheckConstraint("ck_orders_dh03_paid", "status <> 'Paid' OR (stockdeducted AND paymentstatus = 'Paid' AND paymentverifiedat IS NOT NULL AND paymentverifiedbyuserid IS NOT NULL AND paymentreviewedat IS NOT NULL AND paymentreviewedbyuserid = paymentverifiedbyuserid AND finalfulfilledamount IS NOT NULL)");

                            t.HasCheckConstraint("ck_orders_dh03_status", "status IN ('Pending', 'Paid', 'Processed', 'Shipped', 'Delivered', 'Cancelled', 'Refunded')");

                            t.HasCheckConstraint("ck_orders_dh03_stock_owner", "NOT stockdeducted OR status IN ('Paid', 'Processed', 'Shipped', 'Delivered')");

                            t.HasCheckConstraint("ck_orders_finalfulfilledamount_range", "finalfulfilledamount IS NULL OR (finalfulfilledamount >= 0 AND finalfulfilledamount <= totalamount)");

                            t.HasCheckConstraint("ck_orders_payment_review_pair", "(paymentreviewedat IS NULL) = (paymentreviewedbyuserid IS NULL)");

                            t.HasCheckConstraint("ck_orders_payment_verification_pair", "(paymentverifiedat IS NULL) = (paymentverifiedbyuserid IS NULL)");

                            t.HasCheckConstraint("ck_orders_totalamount_nonnegative", "totalamount >= 0");

                            t.HasCheckConstraint("ck_orders_workflowstate", "workflowstate IS NULL OR workflowstate IN ('ConflictAwaitingDecision', 'ConflictResolvedContinue', 'ConflictResolvedCancel')");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("accountname");

                    b.Property<string>("Accountnumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accountnumber");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Fulladdress")
                        .HasColumnType("text")
                        .HasColumnName("fulladdress");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<string>("Paymentimagepath")
                        .HasColumnType("text")
                        .HasColumnName("paymentimagepath");

                    b.Property<string>("Paymentmethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymentmethod");

                    b.Property<string>("Paymentnotes")
                        .HasColumnType("text")
                        .HasColumnName("paymentnotes");

                    b.Property<string>("Recipientname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("recipientname");

                    b.Property<string>("Recipientphone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipientphone");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("Transferreferencenumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transferreferencenumber");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("orderdetails_pkey");

                    b.HasIndex(new[] { "Orderid" }, "IX_orderdetails_orderid")
                        .IsUnique();

                    b.ToTable("orderdetails", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appliedpromotionid")
                        .HasColumnType("integer")
                        .HasColumnName("applied_promotion_id");

                    b.Property<string>("Appliedpromotionsjson")
                        .HasColumnType("jsonb")
                        .HasColumnName("applied_promotions_json");

                    b.Property<string>("Appliedpromotiontitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("applied_promotion_title");

                    b.Property<decimal>("Discountamount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("Finalunitprice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("final_unit_price");

                    b.Property<int>("Freequantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("free_quantity");

                    b.Property<int?>("FulfilledQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("fulfilled_quantity");

                    b.Property<int>("Orderid")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<decimal>("Originalunitprice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("original_unit_price");

                    b.Property<int>("Productid")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("RetailPriceId")
                        .HasColumnType("integer")
                        .HasColumnName("retail_price_id");

                    b.Property<int?>("RetailSizeMl")
                        .HasColumnType("integer")
                        .HasColumnName("retail_size_ml");

                    b.Property<int?>("UnavailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("unavailable_quantity");

                    b.Property<decimal>("Unitprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unitprice");

                    b.HasKey("Id")
                        .HasName("orderitems_pkey");

                    b.HasIndex("RetailPriceId");

                    b.HasIndex(new[] { "Orderid" }, "IX_orderitems_orderid");

                    b.HasIndex(new[] { "Productid" }, "IX_orderitems_productid");

                    b.ToTable("orderitems", null, t =>
                        {
                            t.HasCheckConstraint("ck_orderitems_fulfilled_quantity_range", "fulfilled_quantity IS NULL OR (fulfilled_quantity >= 0 AND fulfilled_quantity <= quantity)");

                            t.HasCheckConstraint("ck_orderitems_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orderitems_unavailable_quantity_range", "unavailable_quantity IS NULL OR (unavailable_quantity >= 0 AND unavailable_quantity <= quantity)");

                            t.HasCheckConstraint("ck_orderitems_unitprice_nonnegative", "unitprice >= 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Paymentmethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accountholdername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accountholdername");

                    b.Property<string>("Accountnumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accountnumber");

                    b.Property<string>("Cardcolor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cardcolor");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Storesettingsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("storesettingsid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("paymentmethods_pkey");

                    b.HasIndex(new[] { "Storesettingsid" }, "ix_paymentmethods_storesettingsid");

                    b.ToTable("paymentmethods", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("brand");

                    b.Property<int>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Imageurl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsRetailEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_retail_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("SalesLastUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sales_last_updated_at");

                    b.Property<string>("StockUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Piece")
                        .HasColumnName("stock_unit");

                    b.Property<int>("Stockquantity")
                        .HasColumnType("integer")
                        .HasColumnName("stockquantity");

                    b.Property<int>("TotalSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_sold");

                    b.Property<int?>("VolumeMl")
                        .HasColumnType("integer")
                        .HasColumnName("volume_ml");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex(new[] { "Brand" }, "ix_products_brand_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Brand" }, "ix_products_brand_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Brand" }, "ix_products_brand_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Categoryid", "Createdat" }, "ix_products_categoryid_createdat")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "Createdat" }, "ix_products_createdat")
                        .IsDescending();

                    b.HasIndex(new[] { "Description" }, "ix_products_description_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Description" }, "ix_products_description_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Description" }, "ix_products_description_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Name" }, "ix_products_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_products_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_products_name_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "TotalSold" }, "ix_products_total_sold");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price_nonnegative", "price >= 0");

                            t.HasCheckConstraint("ck_products_retail_requires_ml", "(is_retail_enabled = false) OR (stock_unit = 'Ml' AND volume_ml IS NOT NULL AND volume_ml > 0)");

                            t.HasCheckConstraint("ck_products_stock_unit", "stock_unit IN ('Piece', 'Ml')");

                            t.HasCheckConstraint("ck_products_stockquantity_nonnegative", "stockquantity >= 0");

                            t.HasCheckConstraint("ck_products_volume_for_ml", "(stock_unit = 'Piece' AND volume_ml IS NULL) OR (stock_unit = 'Ml' AND volume_ml IS NOT NULL AND volume_ml > 0)");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.ProductRetailPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("SizeMl")
                        .HasColumnType("integer")
                        .HasColumnName("size_ml");

                    b.HasKey("Id")
                        .HasName("product_retail_prices_pkey");

                    b.HasIndex(new[] { "SizeMl" }, "ix_product_retail_prices_active_size")
                        .HasFilter("is_active AND size_ml > 0 AND price > 0");

                    b.HasIndex(new[] { "ProductId", "SizeMl" }, "ux_product_retail_prices_product_size")
                        .IsUnique();

                    b.ToTable("product_retail_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_retail_prices_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_product_retail_prices_size_positive", "size_ml > 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("banner_image");

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("buy_quantity");

                    b.Property<bool>("CanBeCombined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_be_combined");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("FreeQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("free_quantity");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("minimum_amount");

                    b.Property<decimal?>("OfferPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("offer_price");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("priority");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("promotion_type");

                    b.Property<int>("SpendDiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("spend_discount_type");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("All")
                        .HasColumnName("target_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("promotions_pkey");

                    b.HasIndex(new[] { "IsActive", "StartDate", "EndDate" }, "idx_promotions_active_dates");

                    b.HasIndex(new[] { "Priority", "CreatedAt" }, "idx_promotions_priority");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.PromotionCategory", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("integer")
                        .HasColumnName("promotion_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PromotionId", "CategoryId")
                        .HasName("pk_promotion_categories");

                    b.HasIndex(new[] { "CategoryId" }, "idx_promotion_categories_category");

                    b.ToTable("promotion_categories", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.PromotionProduct", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("integer")
                        .HasColumnName("promotion_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PromotionId", "ProductId")
                        .HasName("pk_promotion_products");

                    b.HasIndex(new[] { "ProductId" }, "idx_promotion_products_product");

                    b.ToTable("promotion_products", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("YER")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal>("DiscountTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_total");

                    b.Property<long>("DraftRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("draft_revision");

                    b.Property<DateTime?>("EditLockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edit_lock_expires_at");

                    b.Property<string>("EditLockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("edit_locked_by");

                    b.Property<Guid?>("EditSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edit_session_id");

                    b.Property<decimal>("FinalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("final_amount");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("ManualDiscountTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("manual_discount_total");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PromotionDiscountTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("promotion_discount_total");

                    b.Property<string>("PromotionSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("promotion_snapshot_json");

                    b.Property<int>("SalesDayId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_day_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("sales_pkey");

                    b.HasIndex(new[] { "InvoiceNumber" }, "ix_sales_invoice_number")
                        .IsUnique();

                    b.HasIndex(new[] { "SalesDayId", "Status" }, "ix_sales_sales_day_status");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_amounts_nonnegative", "total_amount >= 0 AND discount_total >= 0 AND final_amount >= 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedPromotionId")
                        .HasColumnType("integer")
                        .HasColumnName("applied_promotion_id");

                    b.Property<string>("AppliedPromotionTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("applied_promotion_title");

                    b.Property<decimal>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount");

                    b.Property<decimal>("FinalUnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("final_unit_price");

                    b.Property<decimal>("ManualDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("manual_discount_amount");

                    b.Property<decimal>("OriginalUnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("original_unit_price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("PromotionDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("promotion_discount_amount");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<int?>("RetailPriceId")
                        .HasColumnType("integer")
                        .HasColumnName("retail_price_id");

                    b.Property<int?>("RetailSizeMl")
                        .HasColumnType("integer")
                        .HasColumnName("retail_size_ml");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("sale_items_pkey");

                    b.HasIndex("RetailPriceId");

                    b.HasIndex(new[] { "ProductId" }, "ix_sale_items_product_id");

                    b.HasIndex(new[] { "SaleId" }, "ix_sale_items_sale_id");

                    b.ToTable("sale_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaleItem_Quantity_Positive", "quantity > 0");

                            t.HasCheckConstraint("ck_sale_items_amounts_nonnegative", "unit_price >= 0 AND discount >= 0 AND total >= 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SalePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id")
                        .HasName("sale_payments_pkey");

                    b.HasIndex(new[] { "PaymentMethodId" }, "ix_sale_payments_payment_method_id");

                    b.HasIndex(new[] { "SaleId" }, "ix_sale_payments_sale_id");

                    b.ToTable("sale_payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalePayment_Amount_Positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SalesDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("NetTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("net_total");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("OpeningBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("opening_balance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Open'::character varying");

                    b.Property<decimal>("TotalCash")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_cash");

                    b.Property<decimal>("TotalReturns")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_returns");

                    b.Property<decimal>("TotalSales")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_sales");

                    b.Property<decimal>("TotalTransfer")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_transfer");

                    b.Property<decimal>("TotalWallet")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_wallet");

                    b.HasKey("Id")
                        .HasName("sales_days_pkey");

                    b.HasIndex(new[] { "CreatedBy", "Status" }, "ux_sales_days_created_by_open")
                        .IsUnique()
                        .HasFilter("status = 'Open'");

                    b.ToTable("sales_days", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_days_opening_balance_nonnegative", "opening_balance >= 0");

                            t.HasCheckConstraint("ck_sales_days_totals_nonnegative", "total_sales >= 0 AND total_cash >= 0 AND total_transfer >= 0 AND total_wallet >= 0 AND total_returns >= 0 AND net_total >= 0");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Securitylog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Deviceinfo")
                        .HasColumnType("text")
                        .HasColumnName("deviceinfo");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipaddress");

                    b.Property<int?>("Riskscore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("riskscore");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("securitylogs_pkey");

                    b.HasIndex("Userid");

                    b.ToTable("securitylogs", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SiteStateEventReceipt", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliveryid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<byte[]>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payloadsha256");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordedatutc");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.HasKey("DeliveryId")
                        .HasName("site_state_event_receipts_pkey");

                    b.HasIndex(new[] { "SiteId", "Revision" }, "ix_site_state_event_receipts_site_revision");

                    b.ToTable("site_state_event_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_site_state_event_receipts_decision", "decision IN ('Applied', 'Equal', 'EqualConflict', 'Stale')");

                            t.HasCheckConstraint("ck_site_state_event_receipts_hash_length", "octet_length(payloadsha256) = 32");

                            t.HasCheckConstraint("ck_site_state_event_receipts_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_site_state_event_receipts_site_id", "siteid = 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SiteStateSyncCheckpoint", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("siteid");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutivefailures");

                    b.Property<DateTimeOffset>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastattemptatutc");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lastfailurecode");

                    b.Property<long?>("LastObservedRemoteRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("lastobservedremoterevision");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastsuccessatutc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedatutc");

                    b.HasKey("SiteId")
                        .HasName("site_state_sync_checkpoints_pkey");

                    b.ToTable("site_state_sync_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_site_state_sync_checkpoints_failures", "consecutivefailures >= 0");

                            t.HasCheckConstraint("ck_site_state_sync_checkpoints_remote_revision", "lastobservedremoterevision IS NULL OR lastobservedremoterevision >= 1");

                            t.HasCheckConstraint("ck_site_state_sync_checkpoints_site_id", "siteid = 1");
                        });
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Storesetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contactemail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("contactemail")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Currencycode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("YER")
                        .HasColumnName("currency_code");

                    b.Property<int?>("Featuredcategoryid")
                        .HasColumnType("integer")
                        .HasColumnName("featuredcategoryid");

                    b.Property<string>("Heromarketingdesc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("heromarketingdesc")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Heromarketingtext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("heromarketingtext")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Instagramlink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("instagramlink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Tiktoklink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("tiktoklink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Twitterlink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("twitterlink")
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("Whatsappnumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("whatsappnumber")
                        .HasDefaultValueSql("''::text");

                    b.HasKey("Id")
                        .HasName("storesettings_pkey");

                    b.ToTable("storesettings", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'Customer'::character varying");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "ux_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "ux_users_phone")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.UserSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("'Customer'::character varying");

                    b.Property<int>("SearchNameSyncVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("SearchNameSyncVersion");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("UserSite_pkey");

                    b.HasAlternateKey("UserId")
                        .HasName("AK_UserSite_UserID");

                    b.ToTable("UserSite", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("browser");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Device")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("device");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("governorate");

                    b.Property<DateTime>("Visitdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visitdate")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP + '03:00:00'::interval)");

                    b.Property<string>("Visitorname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("visitorname");

                    b.HasKey("Id")
                        .HasName("visits_pkey");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Carts")
                        .HasForeignKey("Userid")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_cart");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cartitem", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Cart", "Cart")
                        .WithMany("Cartitems")
                        .HasForeignKey("Cartid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart");

                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("Cartitems")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_cart");

                    b.HasOne("YAGOT_2._0.Models.ProductRetailPrice", "RetailPrice")
                        .WithMany("Cartitems")
                        .HasForeignKey("RetailPriceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cartitems_retail_price");

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("RetailPrice");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Deliveryorder", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Order", null)
                        .WithOne("Deliveryorder")
                        .HasForeignKey("YAGOT_2._0.Models.Deliveryorder", "Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Orders")
                        .HasForeignKey("Userid")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_order");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderdetail", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Order", "Order")
                        .WithOne("Orderdetail")
                        .HasForeignKey("YAGOT_2._0.Models.Orderdetail", "Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orderdetails_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Orderitem", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Order", "Order")
                        .WithMany("Orderitems")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order");

                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("Orderitems")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_order");

                    b.HasOne("YAGOT_2._0.Models.ProductRetailPrice", "RetailPrice")
                        .WithMany("Orderitems")
                        .HasForeignKey("RetailPriceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orderitems_retail_price");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("RetailPrice");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Paymentmethod", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Storesetting", "Storesettings")
                        .WithMany("Paymentmethods")
                        .HasForeignKey("Storesettingsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paymentmethods_storesettings");

                    b.Navigation("Storesettings");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.ProductRetailPrice", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("RetailPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_retail_prices_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.PromotionCategory", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_categories_categories");

                    b.HasOne("YAGOT_2._0.Models.Promotion", "Promotion")
                        .WithMany("PromotionCategories")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_categories_promotions");

                    b.Navigation("Category");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.PromotionProduct", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_products_products");

                    b.HasOne("YAGOT_2._0.Models.Promotion", "Promotion")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_products_promotions");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Sale", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.SalesDay", "SalesDay")
                        .WithMany("Sales")
                        .HasForeignKey("SalesDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_sales_day");

                    b.Navigation("SalesDay");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SaleItem", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_product");

                    b.HasOne("YAGOT_2._0.Models.ProductRetailPrice", "RetailPrice")
                        .WithMany("SaleItems")
                        .HasForeignKey("RetailPriceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sale_items_retail_price");

                    b.HasOne("YAGOT_2._0.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_sale");

                    b.Navigation("Product");

                    b.Navigation("RetailPrice");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SalePayment", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.Paymentmethod", "PaymentMethod")
                        .WithMany("SalePayments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_payments_payment_method");

                    b.HasOne("YAGOT_2._0.Models.Sale", "Sale")
                        .WithMany("SalePayments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_payments_sale");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Securitylog", b =>
                {
                    b.HasOne("YAGOT_2._0.Models.UserSite", null)
                        .WithMany("Securitylogs")
                        .HasForeignKey("Userid")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_logs");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Cart", b =>
                {
                    b.Navigation("Cartitems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Order", b =>
                {
                    b.Navigation("Deliveryorder");

                    b.Navigation("Orderdetail");

                    b.Navigation("Orderitems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Paymentmethod", b =>
                {
                    b.Navigation("SalePayments");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Product", b =>
                {
                    b.Navigation("Cartitems");

                    b.Navigation("Orderitems");

                    b.Navigation("RetailPrices");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.ProductRetailPrice", b =>
                {
                    b.Navigation("Cartitems");

                    b.Navigation("Orderitems");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Promotion", b =>
                {
                    b.Navigation("PromotionCategories");

                    b.Navigation("PromotionProducts");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("SalePayments");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.SalesDay", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.Storesetting", b =>
                {
                    b.Navigation("Paymentmethods");
                });

            modelBuilder.Entity("YAGOT_2._0.Models.UserSite", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Securitylogs");
                });
#pragma warning restore 612, 618
        }
    }
}
