CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802192155_StoreSettingsDatabaseSync') THEN
    CREATE TABLE IF NOT EXISTS storesettings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        whatsappnumber character varying(20) NOT NULL DEFAULT '',
        contactemail character varying(255) NOT NULL DEFAULT '',
        instagramlink character varying(500) NOT NULL DEFAULT '',
        twitterlink character varying(500) NOT NULL DEFAULT '',
        tiktoklink character varying(500) NOT NULL DEFAULT '',
        brandsmarquee text NOT NULL DEFAULT '',
        featuredcategoryid integer,
        heromarketingtext character varying(500) NOT NULL DEFAULT '',
        heromarketingdesc text NOT NULL DEFAULT '',
        omqiaccountname character varying(255) NOT NULL DEFAULT '',
        omqiaccountnumber character varying(50) NOT NULL DEFAULT '',
        busairiaccountname character varying(255) NOT NULL DEFAULT '',
        busairiaccountnumber character varying(50) NOT NULL DEFAULT '',
        bindowalaccountname character varying(255) NOT NULL DEFAULT '',
        bindowalaccountnumber character varying(50) NOT NULL DEFAULT '',
        otherpaymentinstructions text NOT NULL DEFAULT '',
        shippingfee numeric(10,2) NOT NULL DEFAULT 0,
        freeshippingthreshold numeric(10,2) NOT NULL DEFAULT 0,
        CONSTRAINT storesettings_pkey PRIMARY KEY (id)
    );

    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS whatsappnumber character varying(20) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS contactemail character varying(255) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS instagramlink character varying(500) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS twitterlink character varying(500) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS tiktoklink character varying(500) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS brandsmarquee text NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS featuredcategoryid integer;
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS heromarketingtext character varying(500) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS heromarketingdesc text NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS omqiaccountname character varying(255) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS omqiaccountnumber character varying(50) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS busairiaccountname character varying(255) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS busairiaccountnumber character varying(50) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS bindowalaccountname character varying(255) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS bindowalaccountnumber character varying(50) NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS otherpaymentinstructions text NOT NULL DEFAULT '';
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS shippingfee numeric(10,2) NOT NULL DEFAULT 0;
    ALTER TABLE storesettings ADD COLUMN IF NOT EXISTS freeshippingthreshold numeric(10,2) NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260802192155_StoreSettingsDatabaseSync') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260802192155_StoreSettingsDatabaseSync', '9.0.0');
    END IF;
END $EF$;
COMMIT;

